TD-74::add filter to show pod's url in kibana
valitydev/botkube pull request #1
Opened 2022-02-11 08:41 UTC by ivnmrtk

##### ISSUE TYPE

 - Feature Pull Request

##### SUMMARY

2022-02-11 10:53 UTC, vilorij commented on pkg/filterengine/filters/deploy_errors_checker.go
> +	KibanaUrlTemplate = "https://kibana.empayre.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!('@severity',message,kubernetes.pod.name),f
Вроде там маркдаун поддерживается, Стоит сделать что-то типа
[LOOK POD LOGS](https://kibana.empayre.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!('@severity',message,kubernetes.pod.name),filters:!(),index:filebeat-rbkmoney-processing,interval:auto,query:(language:kuery,query:'kubernetes.pod.name:%20%22%s%22'),sort:!()))

2022-02-11 10:53 UTC, vilorij commented on pkg/filterengine/filters/deploy_errors_checker.go
> +	KibanaUrlTemplate = "https://kibana.empayre.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!('@severity',message,kubernetes.pod.name),f
Иначе канал будет в больших по размеру нотифах, что не очень, имхо

2022-02-11 11:01 UTC, tolkonepiu requested changes

2022-02-11 11:01 UTC, tolkonepiu commented on pkg/filterengine/filters/deploy_errors_checker.go
> +	KibanaUrlTemplate = "https://kibana.empayre.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!('@severity',message,kubernetes.pod.name),f
Тут идет упоминание доменов и неймингов, что не оч хорошо. Это можно все прокинуть в конфигурацию?

2022-02-11 11:08 UTC, vilorij commented on pkg/filterengine/filters/deploy_errors_checker.go
> +	KibanaUrlTemplate = "https://kibana.empayre.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!('@severity',message,kubernetes.pod.name),f
Чувствую, считывание кастомных конфигов потребует больше изменений, чем использование уже существующего механизма. 
наверно, проще будет унести это в приватную часть реп, если критично

2022-02-11 11:48 UTC, ivnmrtk commented on pkg/filterengine/filters/deploy_errors_checker.go
> +	KibanaUrlTemplate = "https://kibana.empayre.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!('@severity',message,kubernetes.pod.name),f
Мне казалось, что сообщения отправляются в виде preformatted code block в mm, внутри которого маркдаун вкрячить не получается. Но скорее всего это только поля Recommendations касается, посмотрю, что с этим можно сделать

2022-02-11 16:24 UTC, tolkonepiu commented on pkg/filterengine/filters/deploy_errors_checker.go
> +	KibanaUrlTemplate = "https://kibana.empayre.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!('@severity',message,kubernetes.pod.name),f
Давайте так, но надо учесть, что и kibana. скоро сменится на opensearch.

2022-02-11 16:25 UTC, tolkonepiu commented on pkg/filterengine/filters/deploy_errors_checker.go
> +	KibanaUrlTemplate = "https://kibana.empayre.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!('@severity',message,kubernetes.pod.name),f
Вообще на самом деле у mm есть плагин autolink
https://github.com/mattermost/mattermost-plugin-autolink

Может быть стоит попробовать через него даже, а здесь просто будет строка поиска

2022-02-16 14:06 UTC, ivnmrtk commented
Вынес урл в конфигурацию и добавил для него в структуру Event отдельное поле - так оно будет конкатенироваться отдельно, а не внутри маркдауновского code block, как было с полем recommendations, поэтому возиться с плагином тоже не придется

2022-02-16 18:02 UTC, tolkonepiu commented on pkg/filterengine/filters/deploy_errors_checker.go
> +	if err != nil {
ох уж этот go)

2022-02-16 18:02 UTC, tolkonepiu approved these changes

2022-02-17 07:48 UTC, merged